### ISSUE TITLE
Dot does not correctly work with Dynamic Resolution

### ISSUE THREAD

**Issue by RorschachsDream** [Haplo064/PixelPerfect#21]
The new Dynamic Resolution feature if set to on causes the dot to displace.

Example: https://i.imgur.com/VaNKM8c.png

**Comment by jacob-keller** [comment]
I noticed this happening mainly on specific jobs such as dark knight

**Comment by Haplo064** [comment]
Yeah, it's dynamic resolution. It's altering your resolution (which the dot plugin relies on to know where to draw) so each change causes the plugin to move.

There's talk of fixing the root problem in Dalamud, so I'm not sure i'll implement a fix for it in the plugin.

**Comment by jacob-keller** [comment]
Ok. I guess it happens more in graphically intensive skills popping up which explains why I mostly noticed it with dark. I just disabled the dynamic resolution for now anyways

**Comment by Haplo064** [comment]
Resolved.
