### ISSUE TITLE
Editor scale can cause freeze

### ISSUE THREAD

**Issue by blackbunny208** [Haplo064/PixelPerfect#24]
Accidentally setting the scale to 0 in the editor freezes the game instantly.  This is in v3.0.0.0.

**Comment by Haplo064** [comment]
Oh shit, yes that would do that.
Fixed and will be updated soon (not soon:tm:, actually soon.)

**Comment by blackbunny208** [comment]
lol, you're the best!

**Comment by Haplo064** [comment]
Fixed
