### ISSUE TITLE
Checkbox for Jobs instead of Dropdown

### ISSUE THREAD

**Issue by DJFarr** [Haplo064/PixelPerfect#25]
Hi, Love the new changes!

I noticed that each line has a dropdown for the Job that it is visible for, which I believe to be quite limiting.

Take for example: "I want a melee-range (3-yalm) ring to appear for all my melee Jobs, but not to appear for all my casters/ranged".
I would need 1 ring per melee job, with each ring being simply a duplicate set to a different Job.

Instead of a dropdown for a single job, a checklist approach that allows multiple jobs to be ticked for each ring would be ideal IMO.

Hope this makes sense and is feasible :)

**Comment by Haplo064** [comment]
Added.
