### ISSUE TITLE
Feature Request: 3 suggestions for more customizable lines

### ISSUE THREAD

**Issue by DJFarr** [Haplo064/PixelPerfect#26]
Hi, as mentioned in a previous issue regarding Job dropdowns, I love the changes you've made.

I know it must've been a lot of effort to do the overhaul, but I thought I'd just spitball ideas that crossed my mind while using the new UI.

### 1. Alternate controls for position of Lines
The idea here is just for more QoL controls for adjusting lines at angles. It would have 3 controls: Origin (x + y), Angle  (degrees), and Length (yalms obviously). denoted as the green arrows in the pic:
![2023-01-16 20_24_50-NVIDIA GeForce Overlay DT](https://user-images.githubusercontent.com/16067714/212653046-88887db4-6807-47ce-898b-e23f0f1fe969.jpg)

### 2. Addition of Arcs
This would just be the same as adding a circle, but with the additional option of slicing it at certain points (i.e. a set angle away from the relative direction, as seen in the below pic:
![2023-01-16 20_31_32-NVIDIA GeForce Overlay DT](https://user-images.githubusercontent.com/16067714/212653337-de5ec59b-6aed-45f5-9b91-e91e9c8605bb.jpg)

### 3. Target-relative
This one would be a little annoying, as it would involve added tracking of target position.
I personally think it would be very cool to use the combination of the above two features to create a cone, and then point it at the currently selected target. As per the below pic:
![2023-01-16 20_35_35-NVIDIA GeForce Overlay DT](https://user-images.githubusercontent.com/16067714/212653603-12217657-264c-42af-b92d-b20e46c54bdb.jpg)
This would be perfect for those AoE abilities which have cones facing the target.

Once again, this is no demand for more features, I just think the addition of these could make the tool even more useful.
Thanks :)

**Comment by Spacellary** [comment]
Oooh nice DJFarr! Good stuff!

**Comment by Haplo064** [comment]
Arcs and Cones are in progress.
Relative to target is actually easier than you'd think.
Additional line controls will be added.

**Comment by Haplo064** [comment]
Only took a year and a half.
Option 2 and 3 are added, and I likely won't be adding option 1.
