### ISSUE TITLE
Feature Request: Opacity

### ISSUE THREAD

**Issue by iyu46** [Haplo064/PixelPerfect#27]
Hi! The new editor is really interesting because it's so flexible! I was just wondering if it was possible to add (or re-add? my memory is kinda bad) opacity options! 

For example, [here](https://github.com/Haplo064/PixelPerfect/blob/master/PixelPerfect/Doodles.cs#L97) you could pass a float for the second argument to GetColorU32 for the alpha value, right? :0

**Comment by DJFarr** [comment]
This is possible in the colour-picker window (the A (alpha) block):
![2023-01-16 22_43_40-FINAL FANTASY XIV - Copy](https://user-images.githubusercontent.com/16067714/212675876-df80ed0e-1342-441d-b9b7-f77461603c01.jpg)

**Comment by iyu46** [comment]
I am very embarrassed and going to pass away now thank you so much
