### ISSUE TITLE
Changelog opens on every game boot

### ISSUE THREAD

**Issue by FridgeRacer** [Haplo064/PixelPerfect#30]
After the latest update, the changelog opens on the main menu every time I boot the game up. I couldn't personally find anything interesting in the log, but I attached it anyways. If this behaviour is intentional, my apologies!

[dalamud.log.txt](https://github.com/Haplo064/PixelPerfect/files/10440037/dalamud.log.txt)

**Comment by chennin** [comment]
I hope it's not intentional. Please advise on how to stop the popup from appearing every time, if possible.

**Comment by Haplo064** [comment]
This is not intentional, and fixed on my local build.
To fix manually in the meantime, open and close your config.
