### ISSUE TITLE
Game Crashes w/ Cause

### ISSUE THREAD

**Issue by michaelm600279** [Haplo064/PixelPerfect#31]
Just noticed that the new PP reset my config. All fine and dandy, however before I was able to create a pixel with an "outline", as in, black in the center of the pixel indicator with a white circular border around it. **What this did is create a contrast on the pixel that allows you to see it no matter the floor color within Final Fantasy. This was a critical feature as some arena floors are bright colored and having a solid color pixel can blend in with the floor.** 

In an attempt to replicate the old configuration, I was messing around with the settings. I turned the "segments" up to 1000 and noticed the pixel shape contorted. I added one more 0 to make it 10000 and it instantly crashed my game. The setting shouldn't be allowed over values that crash the game.

Additionally, please add back the "border" feature or let me know how I can do this. I'm attaching an image showing how close I can get to the black dot with white border. This instance however has a transparent center, meaning the color of the floor comes through the pixel and makes it harder to see.

I also used to have a true north indicator but can't seem to find how to do that now.

![image](https://user-images.githubusercontent.com/62119073/213064628-c4767deb-9156-4c0c-8e4f-1a0866455432.png)
![image](https://user-images.githubusercontent.com/62119073/213064643-32fe935b-4a24-4f87-97cf-4601f801b626.png)

**Comment by Haplo064** [comment]
To add a border, simply create another dot that is slightly larger than the dot you wish to have a border around.
It's how the old code did it, I have only exposed the ability to do it manually.
If you wish for the dot to be filled, please select the "Filled" option, which will make it a fully coloured dot.

I'll take a look at the crash.

**Comment by Haplo064** [comment]
Can confirm that silly large numbers crash the game.
Added sanity checks to numbers.

**Comment by michaelm600279** [comment]
I didn't realize I could make multiple dots and layer them. That's a great solution!
