### ISSUE TITLE
Game Stutters during certain cutscenes or when the camera are getting bumpy/too close with the character

### ISSUE THREAD

**Issue by vincensinsento** [Haplo064/PixelPerfect#4]
This just happened recently after the new patch I think, I've had no problem at all before, but it starts to kinda get annoying when the camera closes in to my character and then the game stutters a few time.
I tried enabling and disabling the pixel perfect plug-in an it seems the plug-ins causes the freezes.
Any idea how to fix this?
Thanks a lot, I really appreciate this plug-ins.

**Comment by Haplo064** [comment]
Fixed
