### ISSUE TITLE
Update for Endwalker 6.0

### ISSUE THREAD

**Issue by Sekirosucks** [Haplo064/PixelPerfect#6]
Currently not working with the Endwalker expansion - Would there be an update?

**Comment by Haplo064** [comment]
Yep. Soon as I polish off the MSQ I'm working on my plugins again.

**Comment by alkado** [comment]
Need dot. Dot good. Dot is love. Dot is life.

**Comment by wmw** [comment]
Sent PR so Haplo could continue to enjoy MSQ, not sure if this is all that's required as I'm a novice plugin dev, but I tested it locally and it seems to work.

https://github.com/Haplo064/PixelPerfect/pull/7

**Comment by jamescraigbird** [comment]
Hi, thanks for updating for EW. How do we install this? TY

**Comment by Haplo064** [comment]
Forgot to close
