### ISSUE TITLE
Request for additional arrow display

### ISSUE THREAD

**Issue by Tyler4246** [Haplo064/PixelPerfect#9]
I love plugin as is, but I had an idea for an additional feature:

Make a toggleable arrow indicator pointing out from the character's hitbox to true north. This would make keeping your bearings in some fights easier without having to shift focus away from the boss, your character, or your rotation.  Not sure how feasible this is to implement as an additional option or if need be a separate plugin, but would love to use it for certain fights.

Thanks

**Comment by Haplo064** [comment]
Done.
